apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openstack-mcp-server.fullname" . }}
  labels:
    {{- include "openstack-mcp-server.labels" . | nindent 4 }}
data:
  OS_AUTH_URL: {{ .Values.openstack.authUrl | quote }}
  OS_USERNAME: {{ .Values.openstack.username | quote }}
  OS_PROJECT_NAME: {{ .Values.openstack.projectName | quote }}
  OS_REGION_NAME: {{ .Values.openstack.regionName | quote }}
  OS_USER_DOMAIN_NAME: {{ .Values.openstack.userDomainName | quote }}
  OS_PROJECT_DOMAIN_NAME: {{ .Values.openstack.projectDomainName | quote }}
  OSMCP_OS_VERIFY_SSL: {{ .Values.openstack.verifySSL | quote }}
